// Code generated by generate-test-registry. DO NOT EDIT.

package gotest

import (
	ext "github.com/openshift-eng/openshift-tests-extension/pkg/extension/extensiontests"
	gt "github.com/openshift-eng/openshift-tests-extension/pkg/gotest"
)

// Tests contains all the tests to be included in the binary
var Tests = []gt.Test{
	{
		Name:      "TestInformingExample",
		Labels:    []string{},
		Lifecycle: ext.LifecycleBlocking,
		TestFunc:  TestInformingExample,
	},
	{
		Name:      "TestSigTesting",
		Labels:    []string{},
		Lifecycle: ext.LifecycleBlocking,
		TestFunc:  TestSigTesting,
	},
	{
		Name:      "TestSimpleFail",
		Labels:    []string{},
		Lifecycle: ext.LifecycleBlocking,
		TestFunc:  TestSimpleFail,
	},
	{
		Name:      "TestSimplePass",
		Labels:    []string{},
		Lifecycle: ext.LifecycleBlocking,
		TestFunc:  TestSimplePass,
	},
	{
		Name:      "TestSlowOperation",
		Labels:    []string{},
		Lifecycle: ext.LifecycleBlocking,
		TestFunc:  TestSlowOperation,
	},
	{
		Name:      "TestTableDriven",
		Labels:    []string{},
		Lifecycle: ext.LifecycleBlocking,
		TestFunc:  TestTableDriven,
	},
	{
		Name:      "TestWithSkip",
		Labels:    []string{},
		Lifecycle: ext.LifecycleBlocking,
		TestFunc:  TestWithSkip,
	},
	{
		Name:      "TestWithSubtests",
		Labels:    []string{},
		Lifecycle: ext.LifecycleBlocking,
		TestFunc:  TestWithSubtests,
	},
}
